version: '3'
services:
    ###
    postgres-service:
        image: postgres:9.6.17
        container_name: postgres-server
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=awhjw
        volumes: 
            - postgres-data:/var/lib/postgresql/data
        networks: 
            - my-spring-cloud

    ###
    rabbitmq-service:
        image: rabbitmq:3-management
        container_name: rabbitmq-server
        ports:
         - 15672:15672
         - 5672:5672
        networks:
         - my-spring-cloud
networks: 
    my-spring-cloud:

volumes: 
    postgres-data:
        driver: local