spring:
  application:
    name: 'auth-service'
  profiles:
    active: ${PROFILE_TAG:dev}
  cloud:
    config:
      uri: ${CONFIG_SERVER_URI:http://localhost:8888}
      fail-fast: true
      retry:
        max-attempts: 10
  flyway:
    locations: classpath:/db-migrate
#encrypt:
#  key-store:
#    type: jks
#    alias: aliasname
#    location: classpath:/key-for-jwt.jks
#    password: pAss
#    secret: P@ss
#mybatis:
#  type-aliases-package: kr.co.metanet.springauthserver.entity
