spring:
  datasource:
    password: awhjw
    username: postgres
    url: jdbc:postgresql://localhost:5432/oauth2_dev?createDatabaseIfNotExist=true&useSSL=false
  jpa:
    hibernate.ddl-auto: update
    show-sql: true

server:
  port: 7070

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint.health.show-details: always

security:
  oauth2:
    authorization:
      jwt:
        key-store: classpath:/key-for-jwt.jks
        key-password: P@ss
        key-alias: aliasname
        key-store-password: pAss