spring:
  datasource:
    password: ${DB_PASSWORD:awhjw}
    username: ${DB_USER:postgres}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:course_db}?createDatabaseIfNotExist=true&useSSL=false
    jpa.hibernate.ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint.health.show-details: always

security:
  oauth2:
    resource:
      jwt:
        key-store: classpath:/key-for-jwt.jks
        key-password: P@ss
        key-alias: aliasname
        key-store-password: pAss
