eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

server.port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint.health.show-details: always

zuul.routes:
  course-service:
    sensitiveHeaders: Cookie,Set-Cookie
    path: /course-service/**
    url: http://localhost:8081