spring:
    datasource:
        password: awhjw
        username: postgres
        url: jdbc:postgresql://localhost:5432/postgres?createDatabaseIfNotExist=true&useSSL=false
    jpa.hibernate.ddl-auto: update
