spring:
    datasource:
        password: awhjw
        username: postgres
        url: jdbc:postgresql://localhost:5432/schema_style?createDatabaseIfNotExist=true&useSSL=false
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate.ddl-auto: update
        properties:
            hibernate:
                hbm2ddl:
                    auto: update
server:
    port: 8082
